### ISSUE TITLE
_v does not handle highlight of XXX or TODO which Vim auto-highlights

### ISSUE THREAD

**Issue by imran-uk** [trapd00r/utils#2]
_v does not correctly colourize the file when encountering keywords which vim will highlight such as TODO and XXX. Please see attached screenshot for example.

![_v-issue-Screenshot- -Downloads](https://f.cloud.github.com/assets/542530/141986/307b82ba-72a7-11e2-96aa-ad06db3217cf.png)

Thanks for _v - it is an excellent pager for scripts, Apache vhost files etc.

**Comment by trapd00r** [comment]
Pretty sure this was fixed at some point.
![img](http://i.japh.se/_v_xxx.png)
